version: "3.8"

services:
  backend:
    image: neibler/ongil-backend:latest      # 또는 chj78/ongil-backend:latest
    container_name: ongil-backend
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PROD_DB_URL: ${PROD_DB_URL}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ongil-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]