version: "3.8"

services:
  backend:
    image: neibler/ongil-backend:latest      # 또는 chj78/ongil-backend:latest
    container_name: ongil-backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod           # prod 프로필 사용
    ports:
      - "8081:8081"
    env_file:
      - ./env/prod.env                       # 서버 전용 비밀번호 및 기타 설정 저장 파일
