spring:
  datasource:
    url: jdbc:h2:mem:ongil;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # optional: open-in-view 경고 없애고 싶으면
  jpa.open-in-view: false
